### ISSUE TITLE
Player controls unuseable

### ISSUE THREAD

**Issue by nthieberger** [marcolarosa/pdsc-collection-viewer#13]
When playing  media file and transcript (e.g. http://catalog.paradisec.org.au/viewer/#/NT1/98002) the transcript keeps playing but you can't scroll back to the top of the screen to pause it. A solution could be to put a pause / play toggle at each chunk rather than just a the top of the item?

**Comment by nthieberger** [comment]
I can't remember what we discussed about this, but clicking on play still makes the window jump to the top and loses the context of theline clicked on.

**Comment by marcolarosa** [comment]
I think this is resolved in the new viewer.
