### ISSUE TITLE
citation does not resolve

### ISSUE THREAD

**Issue by nthieberger** [marcolarosa/pdsc-collection-viewer#14]
I tried this citation as a way of sending a link to someone, but it doesn't resolve, it hangs, looking for audio.
http://catalog.paradisec.org.au/viewer/#/NT1/98003/NT1-98003-98003B?type=transcript&selected=NT1-98003-98003B.eaf&segment=ts557

**Comment by nthieberger** [comment]
Sorry, I realise this is due to the user not being logged in, but that relates to the issue about having a message for users in this situation advising them to log in to hear the media.

**Comment by marcolarosa** [comment]
Closing this issue for now as there is WIP to deal with the logged in status.
