### ISSUE TITLE
eaf file not working in viewer

### ISSUE THREAD

**Issue by nthieberger** [marcolarosa/pdsc-collection-viewer#29]
This item has an elan (.eaf) transcript that is not being presented in the viewer, but should be.

http://catalog.paradisec.org.au/collections/AC1/items/013

**Comment by marcolarosa** [comment]
I just loaded it up and it was visible in both the transcriptions section and with the audio file. I'm using firefox so the audio didn't load but everything else is ok. What are you seeing?

**Comment by nthieberger** [comment]
Yep, I was looking at the A side, sorry!

**Comment by marcolarosa** [comment]
no worries
